#
# This prebuilds a fully capable minecraft cluster
#

services:
  velocity:
    container_name: rustyconnector_velocity
    image: itzg/bungeecord
    ports:
      - 25565:25577
    environment:
      TYPE: VELOCITY
      VELOCITY_CONFIG: |
        bind: 0.0.0.0:25577
    volumes:
      - ${BASE_PATH}/velocity/plugins:/plugins
      - ${BASE_PATH}/velocity/config:/config
      - velocity_data:/data

  minecraft1:
    container_name: rustyconnector_mc1
    image: itzg/minecraft-server
    environment:
      EULA: "TRUE"
      TYPE: ${MC_TYPE}
      MEMORY: ${RAM}
      USE_AIKAR_FLAGS: ${FLAGS}
    volumes:
      - ${BASE_PATH}/mc1/plugins:/data/plugins
      - ${BASE_PATH}/mc1/mods:/data/mods
      - ${BASE_PATH}/mc1/config:/data/config
      - mc1_data:/data

  minecraft2:
    container_name: rustyconnector_mc2
    image: itzg/minecraft-server
    environment:
      EULA: "TRUE"
      TYPE: ${MC_TYPE}
      MEMORY: ${RAM}
      USE_AIKAR_FLAGS: ${FLAGS}
      UID: 1000
      GID: 1000
      UMASK: "002"
    volumes:
      - ${BASE_PATH}/mc2/plugins:/data/plugins
      - ${BASE_PATH}/mc2/mods:/data/mods
      - ${BASE_PATH}/mc2/config:/data/config
      - mc2_data:/data

  minecraft3:
    container_name: rustyconnector_mc3
    image: itzg/minecraft-server
    environment:
      EULA: "TRUE"
      TYPE: ${MC_TYPE}
      MEMORY: ${RAM}
      USE_AIKAR_FLAGS: ${FLAGS}
      UID: 1000
      GID: 1000
      UMASK: "002"
    volumes:
      - ${BASE_PATH}/mc3/plugins:/data/plugins
      - ${BASE_PATH}/mc3/mods:/data/mods
      - ${BASE_PATH}/mc3/config:/data/config
      - mc3_data:/data

  #
  # Below here are some common tools people might like to use for module development
  #

  redis:
    container_name: rustyconnector_redis
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - ${BASE_PATH}/redis/config:/usr/local/etc/redis
      - redis_data:/data

  postgres:
    container_name: rustyconnector_postgres
    image: postgres:alpine
    environment:
      POSTGRES_USER: rustyconnector
      POSTGRES_PASSWORD: rustyconnector
      POSTGRES_DB: rustyconnector
    ports:
      - 5432:5432
    volumes:
      - ${BASE_PATH}/postgres/config:/etc/postgresql
      - postgres_data:/var/lib/postgresql/data

  mongodb:
    container_name: rustyconnector_mongodb
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: rustyconnector
      MONGO_INITDB_ROOT_PASSWORD: rustyconnector
      MONGO_INITDB_DATABASE: rustyconnector
    ports:
      - 27017:27017
    volumes:
      - ${BASE_PATH}/mongodb/config:/etc/mongo
      - mongodb_data:/data/db

  mariadb:
    container_name: rustyconnector_mariadb
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: rustyconnector
      MYSQL_USER: rustyconnector
      MYSQL_PASSWORD: rustyconnector
      MYSQL_DATABASE: rustyconnector
    ports:
      - 3306:3306
    volumes:
      - ${BASE_PATH}/mariadb/config:/etc/mysql/conf.d
      - mariadb_data:/var/lib/mysql

volumes:
  velocity_data:
  mc1_data:
  mc2_data:
  mc3_data:
  redis_data:
  postgres_data:
  mongodb_data:
  mariadb_data:

networks: {}